### ISSUE TITLE
MissingPropertyException when verifying platforms defined in subprojects

### ISSUE THREAD

**Issue by sacchettom** [nebula-plugins/nebula-publishing-plugin#146]
The IvyRemovePlatformDependencies Plugin will throw `groovy.lang.MissingPropertyException` when platforms are a subproject belonging to the same build.
The issue seems to be in:
https://github.com/nebula-plugins/nebula-publishing-plugin/blob/7e8a83b1027e603c9bf7f0bedf9550dd433e5f9c/src/main/groovy/nebula/plugin/publishing/ivy/PlatformDependencyVerifier.groovy#L62
The safe navigator protects only against null pointers, but in the case of a subproject dependency the returned object will implement `ProjectComponentSelector` rather than `ModuleComponentSelector` and it will not have the requested property defined at all.
Relevant stacktrace:
```
Caused by: groovy.lang.MissingPropertyException: Exception evaluating property 'moduleIdentifier' for java.util.ArrayList, Reason: groovy.lang.MissingPropertyException: No such property: moduleIdentifier for class: org.gradle.internal.component.local.model.DefaultProjectComponentSelector
        at nebula.plugin.publishing.ivy.PlatformDependencyVerifier.platformDependencies(PlatformDependencyVerifier.groovy:61)
        at nebula.plugin.publishing.ivy.PlatformDependencyVerifier$platformDependencies$1.callStatic(Unknown Source)
        at nebula.plugin.publishing.ivy.PlatformDependencyVerifier.memoizedMethodPriv$findPlatformDependenciesProject(PlatformDependencyVerifier.groovy:53)
        at nebula.plugin.publishing.ivy.PlatformDependencyVerifier$__clinit__closure3.doCall(PlatformDependencyVerifier.groovy)
        at nebula.plugin.publishing.ivy.PlatformDependencyVerifier.findPlatformDependencies(PlatformDependencyVerifier.groovy)
        at nebula.plugin.publishing.ivy.PlatformDependencyVerifier$findPlatformDependencies$0.callStatic(Unknown Source)
        at nebula.plugin.publishing.ivy.PlatformDependencyVerifier.checkIfPlatformDependency(PlatformDependencyVerifier.groovy:44)
        at nebula.plugin.publishing.ivy.PlatformDependencyVerifier.isPlatformDependency(PlatformDependencyVerifier.groovy:35)
        at nebula.plugin.publishing.ivy.PlatformDependencyVerifier$isPlatformDependency.call(Unknown Source)
        at nebula.plugin.publishing.ivy.IvyRemovePlatformDependenciesPlugin$_apply_closure1$_closure2$_closure3$_closure4$_closure5.doCall(IvyRemovePlatformDependenciesPlugin.groovy:56)
        at nebula.plugin.publishing.ivy.IvyRemovePlatformDependenciesPlugin$_apply_closure1$_closure2$_closure3$_closure4.doCall(IvyRemovePlatformDependenciesPlugin.groovy:35)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
        at org.gradle.api.internal.UserCodeAction.execute(UserCodeAction.java:38)
        ... 102 more
```

**Comment by rpalcolea** [comment]
Hi @sacchettom , thanks for the report!

This will be fixed in v13.5.1 https://travis-ci.org/nebula-plugins/nebula-publishing-plugin/builds/586152082
