### ISSUE TITLE
Broken compatibility with Gradle 2.3-rc-1

### ISSUE THREAD

**Issue by szpak** [nebula-plugins/nebula-publishing-plugin#28]
It seems that Gradle 2.3 changed the constructor in `org.gradle.api.internal.CompositeDomainObjectSet`. nebula-publishing-plugin
 cannot be built with 2.3-rc-1 itself (see a stacktrace below), but the worse is that every project using nebula-publishing-plugin will not work with Gradle 2.3 (tested with nebula-test).

```
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'nebula-publishing-plugin'.
(...)
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.internal.CompositeDomainObjectSet(java.lang.Class, org.gradle.api.internal.artifacts.DefaultDependencySet)
	at nebula.plugin.publishing.component.CustomUsage$DeferredDependencies.collectPublicDependencies(CustomUsage.groovy:49)
	at nebula.plugin.publishing.component.CustomUsage$DeferredDependencies$collectPublicDependencies$0.callStatic(Unknown Source)
	at nebula.plugin.publishing.component.CustomUsage$DeferredDependencies.collectPublicDependencies(CustomUsage.groovy:44)
	at nebula.plugin.publishing.component.CustomUsage$DeferredDependencies$collectPublicDependencies.call(Unknown Source)
	at nebula.plugin.publishing.component.CustomUsage.getDependencies(CustomUsage.groovy:73)
	at nebula.plugin.publishing.maven.NebulaMavenPublishingPlugin$_fromSoftwareComponent_closure6.doCall(NebulaMavenPublishingPlugin.groovy:199)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
	at org.gradle.api.DomainObjectCollection$all$2.call(Unknown Source)
	at nebula.plugin.publishing.maven.NebulaMavenPublishingPlugin.fromSoftwareComponent(NebulaMavenPublishingPlugin.groovy:186)
	at nebula.plugin.publishing.maven.NebulaMavenPublishingPlugin$_apply_closure1.doCall(NebulaMavenPublishingPlugin.groovy:49)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:201)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
	at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:126)
	at org.gradle.api.DomainObjectCollection$withType$1.call(Unknown Source)
	at org.gradle.api.DomainObjectCollection$withType$1.call(Unknown Source)
	at nebula.plugin.publishing.maven.NebulaBaseMavenPublishingPlugin$_withMavenPublication_closure4_closure9.doCall(NebulaBaseMavenPublishingPlugin.groovy:74)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:201)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
	at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:126)
	at org.gradle.api.DomainObjectCollection$withType.call(Unknown Source)
	at nebula.plugin.publishing.maven.NebulaBaseMavenPublishingPlugin$_withMavenPublication_closure4.doCall(NebulaBaseMavenPublishingPlugin.groovy:72)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
	... 40 more
```

**Comment by rspieldenner** [comment]
Thanks for the check.

Yeah we just saw this at the end of last week when trying to decide if we should upgrade internally to 2.2.1 or wait for 2.3. This plugin is on the list of things to fix. We'll probably lag the release of 2.3 by a few days.

**Comment by bmuschko** [comment]
We haven't tested this code with 2.3 yet which means that we also cannot ensure compatibility. Gradle 2.3 changes a lot of things internally. IMHO we should definitely go for 2.3 first. Incremental steps are better than big bang releases. :-)

**Comment by JakeWharton** [comment]
And the same on 2.3 final. Experiencing this as well.

**Comment by rspieldenner** [comment]
we'll be working on a rewrite of this in the next couple of weeks

**Comment by samatha22** [comment]
Hi, could you please share update on this.

Thanks,
Samatha

**Comment by rspieldenner** [comment]
We have plans to do a complete rewrite to make it cleaner and compatible with gradle 2.3 and newer. I don't have a timeline for getting to it, since internally my company is working on finally transitioning to 2.2.1 internally.

**Comment by rspieldenner** [comment]
2.4.0 should let Maven publishing work in 2.4/2.5
