### ISSUE TITLE
Plugin fails if applied on Gradle 2.3+

### ISSUE THREAD

**Issue by ysb33r** [nebula-plugins/nebula-publishing-plugin#55]
This is the related stacktrace

```
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.internal.CompositeDomainObjectSet(java.lang.Class, org.gradle.api.internal.artifacts.DefaultDependencySet)
	at nebula.plugin.publishing.component.CustomUsage$DeferredDependencies.collectPublicDependencies(CustomUsage.groovy:47)
	at nebula.plugin.publishing.component.CustomUsage$DeferredDependencies$collectPublicDependencies$0.callStatic(Unknown Source)
	at nebula.plugin.publishing.component.CustomUsage$DeferredDependencies.collectPublicDependencies(CustomUsage.groovy:42)
	at nebula.plugin.publishing.component.CustomUsage$DeferredDependencies$collectPublicDependencies.call(Unknown Source)
	at nebula.plugin.publishing.component.CustomUsage.getDependencies(CustomUsage.groovy:71)
	at nebula.plugin.publishing.maven.NebulaMavenPublishingPlugin$_fromSoftwareComponent_closure6.doCall(NebulaMavenPublishingPlugin.groovy:198)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
	at org.gradle.api.DomainObjectCollection$all$2.call(Unknown Source)
	at nebula.plugin.publishing.maven.NebulaMavenPublishingPlugin.fromSoftwareComponent(NebulaMavenPublishingPlugin.groovy:185)
	at nebula.plugin.publishing.maven.NebulaMavenPublishingPlugin$_apply_closure1.doCall(NebulaMavenPublishingPlugin.groovy:49)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:201)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
	at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:126)
	at org.gradle.api.DomainObjectCollection$withType$1.call(Unknown Source)
	at org.gradle.api.DomainObjectCollection$withType$1.call(Unknown Source)
	at nebula.plugin.publishing.maven.NebulaBaseMavenPublishingPlugin$_withMavenPublication_closure4_closure9.doCall(NebulaBaseMavenPublishingPlugin.groovy:74)
```

Tested with version `2.2.2`

**Comment by rspieldenner** [comment]
Move to the 4.x branch please. We had to rewrite
