### ISSUE TITLE
Gradle built-in configuration compileOnly usage breaks publish task

### ISSUE THREAD

**Issue by bronogard** [nebula-plugins/nebula-publishing-plugin#91]
Using:
- Gradle 4.5.1
- Nebula Publish Plugin 6.1.2

build.gradle:
```
plugins {
	id 'java-gradle-plugin'
}


repositories {
	mavenLocal()
	mavenCentral()
}

gradlePlugin {
	plugins {
		anyPlugin {
			id = 'org.bar-any-plugin'
			implementationClass = 'org.any.AnyPlugin'
		}
	}
}

dependencies {
	compileOnly 'com.google.errorprone:error_prone_annotations:2.2.0'
}
```

gradle task:
`gradlew publishToMavenLocal -i -s`

results in:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.bar-any-plugin</groupId>
  <artifactId>org.bar-any-plugin.gradle.plugin</artifactId>
  <version>0.1.0</version>
  <packaging>pom</packaging>
  <dependencyManagement>
    <dependencies/>
  </dependencyManagement>
  <name>any-plugin</name>
  <description/>
  <dependencies>
    <dependency>
      <groupId>com.google.errorprone</groupId>
      <artifactId>error_prone_annotations</artifactId>
      <version>2.2.0</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <dependencies>
    <dependency>
      <groupId>org.bar</groupId>
      <artifactId>any-plugin</artifactId>
      <version>0.1.0</version>
    </dependency>
  </dependencies>
</project>
```

stacktrace:
```
:publishAnyPluginMarkerMavenPublicationToMavenLocal FAILED
:publishAnyPluginMarkerMavenPublicationToMavenLocal (Thread[Task worker for ':',5,main]) completed. Took 0.002 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishAnyPluginMarkerMavenPublicationToMavenLocal'.
> Failed to publish publication 'anyPluginMarkerMaven' to repository 'mavenLocal'
   > Invalid publication 'anyPluginMarkerMaven': POM file is invalid. Check any modifications you have made to the POM file.

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':publishAnyPluginMarkerMavenPublicationToMavenLocal'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:623)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:578)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.artifacts.PublishException: Failed to publish publication 'anyPluginMarkerMaven' to repository 'mavenLocal'
	at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:38)
	at org.gradle.api.publish.maven.tasks.PublishToMavenLocal.publish(PublishToMavenLocal.java:44)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 30 more
Caused by: org.gradle.api.publish.maven.InvalidMavenPublicationException: Invalid publication 'anyPluginMarkerMaven': POM file is invalid. Check any modifications you have made to the POM file.
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.parsePomFileIntoMavenModel(ValidatingMavenPublisher.java:73)
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.validateIdentity(ValidatingMavenPublisher.java:53)
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.publish(ValidatingMavenPublisher.java:44)
	at org.gradle.api.publish.maven.tasks.PublishToMavenLocal$1.publish(PublishToMavenLocal.java:50)
	at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:36)
	... 44 more
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: Duplicated tag: 'dependencies' (position: START_TAG seen ...</dependencies>\r\n  <dependencies>... @27:17) 
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.checkFieldWithDuplicate(MavenXpp3Reader.java:117)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel(MavenXpp3Reader.java:2406)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4088)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4021)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4035)
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.readModelFromPom(ValidatingMavenPublisher.java:84)
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.parsePomFileIntoMavenModel(ValidatingMavenPublisher.java:69)
	... 48 more
```

**Comment by rpalcolea** [comment]
This was probably a Gradle issue and not Nebula

Given this:

```
plugins {
	id 'java-gradle-plugin'
  id "nebula.maven-publish" version "13.4.1"
}


repositories {
	mavenLocal()
	mavenCentral()
}

version = '1.0.0'

gradlePlugin {
	plugins {
		anyPlugin {
			id = 'org.bar-any-plugin'
			implementationClass = 'org.any.AnyPlugin'
		}
	}
}

dependencies {
	compileOnly 'com.google.errorprone:error_prone_annotations:2.2.0'
}

```

and running `./gradlew publishAnyPluginPluginMarkerMavenPublicationToMavenLocal`

MArker looks good

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.bar-any-plugin</groupId>
  <artifactId>org.bar-any-plugin.gradle.plugin</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
  <dependencies>
    <dependency>
      <groupId/>
      <artifactId>test-publishing-plugin</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>
</project>

``` 

Closing this issue now as it should work
